name: angular_modern_charts
description: Angular wrapper for the modern_charts library
version: 0.0.20
homepage: https://www.example.com
author: Dejan Marlovic <dMarlovic83@gmail.com>

environment:
  sdk: '>=2.0.0-dev.23.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+5
  angular_components: ^0.9.0-alpha+4
  angular_forms: 1.0.1-alpha+5
  angular_router: 2.0.0-alpha+5
  sass_builder: ^1.1.2
  modern_charts:
      git: https://www.github.com/afpatmin/modern_charts

dev_dependencies:
  build_runner: ^0.7.10+1
  build_web_compilers: ^0.3.0
  #angular_test: ^1.0.0
  #test: ^0.12.21

dependency_overrides:
  #code_builder: 3.0.3
  #observable: 0.21.0
