name: angular_modern_charts
description: Angular wrapper for the modern_charts library
version: 0.0.20
homepage: https://www.example.com
author: Dejan Marlovic <dMarlovic83@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.2.0  
  modern_charts:
    git: https://github.com/afpatmin/modern_charts
  sass_builder: ^2.1.2
     
dev_dependencies:
  build_runner: ^1.1.3
  json_annotation: ^2.0.0
  json_serializable: ^2.0.1