name: angular_modern_charts
description: Angular wrapper for the modern_charts library
version: 0.0.20
homepage: https://www.example.com
author: Dejan Marlovic <dMarlovic83@gmail.com>

environment:
  sdk: '>=2.0.0-dev.20.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+4
  angular_components: ^0.9.0-alpha+3
  modern_charts:
    git: https://github.com/afpatmin/modern_charts.git
  sass_builder: ^1.1.2
dev_dependencies:
  browser: ^0.10.0

dependency_overrides:
  analyzer: ^0.31.0-alpha.2

transformers:
- sass_builder:
    outputExtension: .scss.css
- angular