name: angular_modern_charts
description: Angular wrapper for the modern_charts library
version: 0.0.20
homepage: https://www.example.com
author: Dejan Marlovic <dMarlovic83@gmail.com>

environment:
  sdk: '>=2.0.0-dev.44.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+11
  angular_components: ^0.9.0-alpha+11
  modern_charts:
    git: https://github.com/afpatmin/modern_charts.git
  sass_builder: ^1.1.5