name: angular_modern_charts
description: Angular wrapper for the modern_charts library
version: 0.1.0
homepage: https://github.com/dejan-marlovic/angular_modern_charts
author: Dejan Marlovic <dmarlovic83@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.2.0  
  modern_charts: 0.1.17
    #git: https://github.com/afpatmin/modern_charts
    #path: ../modern_charts
  sass_builder: ^2.1.2
     
dev_dependencies:
  build_runner: ^1.1.3
  json_annotation: ^2.0.0
  json_serializable: ^2.0.1